from __future__ import annotations

import argparse
import math
import struct
import wave
from pathlib import Path
import tkinter as tk
from tkinter import ttk, messagebox

from foxfunkin.core.paths import project_root
from foxfunkin.core.jsonx import load_json, save_json


def slugify(value: str) -> str:
    out = []
    for ch in value.strip().lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in (" ", "_", "-"):
            out.append("-")
    slug = "".join(out).strip("-")
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug or "my-mod"


def generate_inst_wav(path: Path, bpm: float = 120.0, seconds: float = 24.0):
    path.parent.mkdir(parents=True, exist_ok=True)
    sr = 22050
    total = int(sr * seconds)
    beat_hz = bpm / 60.0
    with wave.open(str(path), "w") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sr)
        for i in range(total):
            t = i / sr
            beat_phase = (t * beat_hz) % 1.0
            step = int(t * beat_hz) % 8
            freq = [220, 247, 262, 294, 330, 294, 262, 247][step]
            env = 0.42 if beat_phase < 0.16 else 0.16
            sample = math.sin(2 * math.pi * freq * t) * env
            if beat_phase < 0.07:
                sample += math.sin(2 * math.pi * 70 * t) * 0.35
            wf.writeframes(struct.pack("<h", int(max(-1, min(1, sample)) * 12000)))


def make_chart(bpm: float, difficulty: str = "normal") -> dict:
    beat = 60000.0 / bpm
    notes = []
    t = 1000.0
    pattern = [4, 5, 6, 7, 4, 6, 5, 7, 7, 5, 6, 4]
    for i in range(48):
        d = pattern[i % len(pattern)]
        n = {"t": round(t, 3), "d": d}
        if i % 12 == 8:
            n["l"] = round(beat * 0.75, 3)
        notes.append(n)
        if i % 4 == 0:
            notes.append({"t": round(t + beat * 0.5, 3), "d": d - 4})
        t += beat * 0.5
    return {
        "version": "2.0.0",
        "scrollSpeed": {"easy": 1.2, "normal": 1.5, "hard": 1.9},
        "events": [
            {"t": 0, "e": "SpawnText", "v": {"text": "New mod loaded", "duration": 1.5}},
            {"t": 2000, "e": "CameraZoom", "v": 1.05}
        ],
        "notes": {
            "easy": notes[::2],
            "normal": notes,
            "hard": notes + [{"t": n["t"] + beat * 0.25, "d": 4 + ((idx + 2) % 4)} for idx, n in enumerate(notes[:24]) if n["d"] >= 4]
        }
    }


def create_mod(root: Path, mod_id: str, title: str, author: str, song_id: str, song_name: str, bpm: float, with_audio: bool = True, enable: bool = True) -> Path:
    mod_id = slugify(mod_id)
    song_id = slugify(song_id)
    mod_root = root / "mods" / mod_id
    song_data = mod_root / "preload" / "data" / "songs" / song_id
    song_audio = mod_root / "songs" / song_id
    graph_dir = mod_root / "graphs"
    song_data.mkdir(parents=True, exist_ok=True)
    song_audio.mkdir(parents=True, exist_ok=True)
    graph_dir.mkdir(parents=True, exist_ok=True)

    save_json(mod_root / "manifest.json", {
        "id": mod_id,
        "title": title or mod_id,
        "version": "1.0.0",
        "author": author or "unknown",
        "enabled": True,
        "description": "Generated by FoxFunkin Mod Wizard.",
        "dependencies": [],
        "priority": 0,
        "entryGraphs": {
            "OnBeat": [],
            "OnStep": [],
            "OnNoteHit": []
        }
    })

    save_json(song_data / f"{song_id}-metadata.json", {
        "version": "2.2.4",
        "songName": song_name or song_id,
        "artist": author or "unknown",
        "charter": author or "unknown",
        "playData": {
            "songVariations": [],
            "difficulties": ["easy", "normal", "hard"],
            "characters": {
                "player": "bf",
                "girlfriend": "gf",
                "opponent": "dad",
                "opponentVocals": [],
                "playerVocals": []
            },
            "stage": "mainStage",
            "noteStyle": "funkin",
            "ratings": { "easy": 1, "normal": 1, "hard": 2 },
            "album": "generated"
        },
        "generatedBy": "FoxFunkin Mod Wizard",
        "timeChanges": [{ "t": 0, "b": 0, "bpm": bpm, "bt": [4, 4, 4, 4] }]
    })
    save_json(song_data / f"{song_id}-chart.json", make_chart(float(bpm)))
    save_json(graph_dir / "intro.fnvgraph.json", {
        "version": "1.0.0",
        "nodes": [
            {"id": "start", "type": "Start", "x": 40, "y": 40, "props": {}},
            {"id": "text", "type": "ShowText", "x": 230, "y": 40, "props": {"text": f"{title or mod_id}", "duration": 2.0}},
            {"id": "shake", "type": "ScreenShake", "x": 460, "y": 40, "props": {"strength": 4, "duration": 0.2}}
        ],
        "links": [{"from": "start", "to": "text"}, {"from": "text", "to": "shake"}]
    })

    if with_audio:
        generate_inst_wav(song_audio / "Inst.wav", bpm=float(bpm), seconds=28)
    else:
        (song_audio / "README_AUDIO.txt").write_text("Put Inst.ogg/mp3/wav here.\n", encoding="utf-8")

    if enable:
        settings = load_json(root / "settings.json", default={})
        enabled = settings.setdefault("mods", {}).setdefault("enabled", [])
        if mod_id not in enabled:
            enabled.append(mod_id)
        save_json(root / "settings.json", settings)

    return mod_root


class WizardGUI(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("FoxFunkin Mod Wizard")
        self.geometry("540x420")
        self.root_path = project_root()
        self.vars = {
            "mod_id": tk.StringVar(value="my-first-mod"),
            "title": tk.StringVar(value="My First Mod"),
            "author": tk.StringVar(value="me"),
            "song_id": tk.StringVar(value="test-song"),
            "song_name": tk.StringVar(value="Test Song"),
            "bpm": tk.StringVar(value="120"),
            "with_audio": tk.BooleanVar(value=True),
            "enable": tk.BooleanVar(value=True),
        }
        self.build()

    def build(self):
        pad = {"padx": 12, "pady": 6}
        frm = ttk.Frame(self)
        frm.pack(fill="both", expand=True, padx=18, pady=18)
        row = 0
        for key, label in [
            ("mod_id", "Mod ID"),
            ("title", "Title"),
            ("author", "Author"),
            ("song_id", "Song ID"),
            ("song_name", "Song Name"),
            ("bpm", "BPM"),
        ]:
            ttk.Label(frm, text=label).grid(row=row, column=0, sticky="w", **pad)
            ttk.Entry(frm, textvariable=self.vars[key], width=34).grid(row=row, column=1, sticky="ew", **pad)
            row += 1
        ttk.Checkbutton(frm, text="Generate original placeholder Inst.wav", variable=self.vars["with_audio"]).grid(row=row, column=0, columnspan=2, sticky="w", **pad)
        row += 1
        ttk.Checkbutton(frm, text="Enable mod in settings.json", variable=self.vars["enable"]).grid(row=row, column=0, columnspan=2, sticky="w", **pad)
        row += 1
        ttk.Button(frm, text="Create working mini-mod", command=self.create).grid(row=row, column=0, columnspan=2, pady=18)
        frm.columnconfigure(1, weight=1)

    def create(self):
        try:
            bpm = float(self.vars["bpm"].get())
            path = create_mod(
                self.root_path,
                self.vars["mod_id"].get(),
                self.vars["title"].get(),
                self.vars["author"].get(),
                self.vars["song_id"].get(),
                self.vars["song_name"].get(),
                bpm,
                self.vars["with_audio"].get(),
                self.vars["enable"].get(),
            )
            messagebox.showinfo("Done", f"Created:\n{path}\n\nRun run.bat and open Freeplay.")
        except Exception as exc:
            messagebox.showerror("Error", str(exc))


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--gui", action="store_true")
    parser.add_argument("--mod-id", default="my-first-mod")
    parser.add_argument("--title", default="My First Mod")
    parser.add_argument("--author", default="me")
    parser.add_argument("--song-id", default="test-song")
    parser.add_argument("--song-name", default="Test Song")
    parser.add_argument("--bpm", type=float, default=120.0)
    parser.add_argument("--no-audio", action="store_true")
    parser.add_argument("--no-enable", action="store_true")
    args = parser.parse_args(argv)

    if args.gui:
        WizardGUI().mainloop()
        return 0

    path = create_mod(
        project_root(), args.mod_id, args.title, args.author,
        args.song_id, args.song_name, args.bpm,
        with_audio=not args.no_audio,
        enable=not args.no_enable,
    )
    print(f"Created {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
